Clean up script/setup
* Fix some issues with codespaces
* Remove code for VSCode that is no longer used
* Install a specific version of neovim
* Make neovim plugin installs headless

diff --git a/script/setup b/script/setup
--- a/script/setup
+++ b/script/setup
@@ -11,12 +11,6 @@ elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]]; then
   export LINUX=1
 fi
 
-if [[ $MACOS ]]; then
-  VSCODE_DIR="$HOME/Library/Application Support/Code/User"
-elif [[ $LINUX ]]; then
-  VSCODE_DIR="$HOME/.config/Code/User"
-fi
-
 function copy_file() {
   local source="$(pwd)/$1"
   local target=$2
@@ -34,27 +28,34 @@ function copy_file() {
   fi
 }
 
+# Codespaces setup
 if [[ -n "$CODESPACES" ]]; then
   chsh -s $(which zsh)
 
   rm ~/.zshrc
   mv ~/.gitconfig ~/.gitconfig.old
-  rm ~/.gitconfig
 
-  wget https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
-
-  apt-get install -y grc ripgrep shellcheck fuse npm fzf ruby-dev
+  apt-get install -y ripgrep shellcheck fuse npm fzf ruby-dev
 
   # Install the latest neovim
-  wget https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
+  wget https://github.com/neovim/neovim/releases/download/v0.6.1/nvim.appimage
   chmod u+x nvim.appimage
   mv nvim.appimage /usr/local/bin/nvim
 
-  npm install -g neovim
-  pip3 install --user neovim
+  if ! [ -x "$(command -v npm)" ]; then
+    echo 'Could not install node neovim plugin' >&2
+  else
+    npm install -g neovim
+  fi
+
+  if ! [ -x "$(command -v pip3)" ]; then
+    echo 'Could not install python neovim plugin' >&2
+  else
+    pip3 install -g neovim
+  fi
 
   # Install neovim plugins
-  nvim +PlugInstall +qall
+  nvim --headless +PlugInstall +qall
 fi
 
 # Standard dotfiles
@@ -114,7 +115,9 @@ elif [[ $LINUX ]]; then
   copy_file VSCode/keybindings.json ~/.config/Code/User/keybindings.json
 fi
 
-for EXTENSION in $(cat VSCode/extensions)
-do
-  code --install-extension $EXTENSION
-done
+if [[ -z "$CODESPACES" ]]; then
+  for EXTENSION in $(cat VSCode/extensions)
+  do
+    code --install-extension $EXTENSION
+  done
+fi
